version: "3"

services:
  portafolioApp: 
    image: node:12.18.0-stretch
    #user: node:node
    working_dir: /home/react
    #command: npm run start
    volumes:
      - ../app:/home/react
    ports:
      - 3000:3000
    tty: true
